import Head from 'next/head';
import classes from '../styles/Home.module.css';
import Link from 'next/link';
import cookie from 'js-cookie';
import Card from '../components/ui/Card';
import React, {useState} from 'react';
import Router from 'next/router';

export default function Home() {

    const [loginError, setLoginError] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    function handleSubmit(e) {
        e.preventDefault();
        fetch('http://localhost:3003/login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ email, password }),
        }).then((r) => {
            return r.json();
        }).then((res) => {
            if (res && res.status === "SUCCESS") {
                setLoginError(res.message);
            }
            if (res && res.data.accessToken) {
                cookie.set('accessToken', res.data.accessToken, {expires: 1});
                Router.push('/');
            }
        });
    }
    const token = cookie.get('accessToken');
    let loggedIn = false;
    if (token) {
        loggedIn = true;
    }
    return (
        <Card>
            {loggedIn && (
                <>
                    <p>You have successfully logged in</p>
                    <Link href="/">
                    <button onClick={() => { cookie.remove('accessToken'); }}>
                        Logout
                    </button>
                    </Link>
                </>
            )}
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {!loggedIn && (
                <>
                    <form className={classes.form} onSubmit={handleSubmit}>
                        <div className={classes.control}>
                            <label htmlFor='title'>Username</label>
                            <input type='email' required id='email' value={email} onChange={(e) => setEmail(e.target.value)} />
                        </div>
                        <div className={classes.control}>
                            <label htmlFor='image'>Password</label>
                            <input type='password' required id='password' value={password} onChange={(e) => setPassword(e.target.value)} />
                        </div>
                        <div className={classes.actions}>
                            <button>Login</button>
                        </div>
                        {/* {loginError && <p style={{color: 'red'}}>{loginError}</p>} */}
                    </form>
                    Not Registered? <Link href="/signup">SignUp</Link>
                </>
            )}
        </Card>
    );
}