import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>Welcome To About</h3>
      <Link href='/'>
        <a>Home</a>
      </Link>
      {/* <Form>
        
      </Form> */}
      </div>
  )
}
