import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import cookie from 'js-cookie';

export default function Home() {
    const token = cookie.get('accessToken');
    let loggedIn = false;
    if (token) {
        loggedIn = true;
    }
    console.log(loggedIn);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h3>Welcome To Next App</h3>
            {loggedIn && (
                <>
                    <p>You have successfully logged in</p>
                    <Link href="/">
                        <button onClick={() => { cookie.remove('accessToken'); }}>
                            Logout
                        </button>
                    </Link>
                </>
            )}
            {!loggedIn && (
            <>
                <Link href="/login">Login</Link>
                <p>or</p>
                <Link href="/signup">SignUp</Link>
            </>
        )}
    </div>
    )
}