import Head from 'next/head'
import cookie from 'js-cookie';
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import React, {useState} from 'react';
import Router from 'next/router';

const Login = () => {
    const [loginError, setLoginError] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    function handleSubmit(e) {
        e.preventDefault();

        fetch('http://localhost:3003/login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ email, password }),
        }).then((r) => {
            return r.json();
        }).then((res) => {
            console.log("login response:"+JSON.stringify(res));
            if (res && res.status === "SUCCESS") {
                setLoginError(res.message);
            }
            if (res && res.data.accessToken) {
                cookie.set('accessToken', res.data.accessToken, {expires: 1});
                Router.push('/');
            }
        });
    }
  return (
    <div className={styles.container}>
        <Head>
            <title>Login</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <form onSubmit={handleSubmit}>
            <h4>Login</h4>
            <input name="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
            <br /> <br />
            <input name="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
            <br /> <br />
            <input type="submit" value="Submit" />
            {loginError && <p style={{color: 'red'}}>{loginError}</p>}
        </form>
        <br /> <br />
        <>
            Not Registered<Link style='color:blue' href="/signup">SignUp</Link>
         </>
    </div>
  );
};

export default Login;
