import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Router, { useRouter } from "next/router"
import React, {useState} from 'react';


const  VerifyOtp = () => {
    const router = useRouter()
    const { query: { id },
    } = router
    const [loginError, setLoginError] = useState('');
    const [otp, setOtp] = useState('');

    function handleSubmit(e) {
        e.preventDefault();
        fetch(`http://localhost:3003/user/${id}/verifyEmail`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ otp }),
        }).then((r) => {
            return r.json();
        }).then((res) => {
            if (res && res.status === "ERROR") {
                setLoginError(res.message);
            }
            if (res && res.status === "SUCCESS") {
                Router.push('/login');
            }
        });
    }
  return (
    <div className={styles.container}>
        <Head>
            <title>Verify OTP</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <form onSubmit={handleSubmit}>
            <h4>Verify Email</h4>
            <input name="otp" type="otp" value={otp} onChange={(e) => setOtp(e.target.value)} />
            <br /> <br />

            <input type="submit" value="Submit" />
            {loginError && <p style={{color: 'red'}}>{loginError}</p>}
        </form>
        <br /> <br />
        <>
           <Link href="/signup">Edit Details, Sign Up</Link>
         </>
    </div>
  );
};

export default VerifyOtp;

