apiVersion: v1
kind: Service
metadata:
  name: next-service
  labels:
    name: next-service
    app: openshift-demo-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30005
  selector:
    name: next-pod
    app: openshift-demo-app