apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: openshift-demo-app
spec:
  type: NodePort
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30004
  selector:
    name: node-pod
    app: openshift-demo-app